name: build-and-push

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "Dockerfile"
      - ".github/workflows/cd.yml"

env:
  ACR: posacrfa01.azurecr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # solo para checkout

    steps:
      # 1. Código fuente de pos-webapp
      - uses: actions/checkout@v4

      # 2. Login directo al ACR
      - name: Docker login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # 3. Build & push imagen
      - name: Build & push image
        run: |
          TAG=${{ github.sha }}
          docker build -t ${ACR}/pos-webapp:${TAG} .
          docker push    ${ACR}/pos-webapp:${TAG}
