name: cd

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "Dockerfile"
      - ".github/workflows/cd.yml"
      - "helm/**"

env:
  ACR: posacrfa01.azurecr.io # ⚠️ igual al de arriba
  RG: myTFResourceGroup
  CLUSTER: pos-aks

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Código de pos-webapp
      - uses: actions/checkout@v4

      # 2) Código de pos-infra (solo charts)  ⬅️ NUEVO
      - name: Checkout pos-infra (charts)
        uses: actions/checkout@v4
        with:
          repository: hectoremilio1000/pos-infra # tu repo de infra
          path: pos-infra # se clona en $GITHUB_WORKSPACE/pos-infra

      # 3) Login a Azure
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 4) Docker login al ACR
      - name: Docker login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # 5) Build & push imagen
      - name: Build & push image
        run: |
          TAG=${{ github.sha }}
          docker build -t ${ACR}/pos-webapp:${TAG} .
          docker push   ${ACR}/pos-webapp:${TAG}
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      # 6) Set AKS context
      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RG }}
          cluster-name: ${{ env.CLUSTER }}
          admin: true

      # 7) Helm upgrade (ruta nueva sin '../')
      - name: Helm upgrade
        run: |
          helm upgrade --install pos-webapp pos-infra/charts/base \
            --values helm/values.yaml \
            --set image.tag=$IMAGE_TAG \
            --namespace default --create-namespace
