name: promote-image

on:
  workflow_run:
    workflows: [build-and-push]
    types: [completed]
    branches: [main]

jobs:
  bump:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    env:
      TAG: ${{ github.event.workflow_run.head_sha }}
      ACR: posacrfa01.azurecr.io

    steps:
      # 1 Clonar repo de infra en subcarpeta "infra"
      - uses: actions/checkout@v4
        with:
          repository: hectoremilio1000/pos-infra
          token: ${{ secrets.GH_TOKEN_INFRA }}
          path: infra

      # 2 Instalar yq (ligero)
      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq \
            https://github.com/mikefarah/yq/releases/download/v4.42.1/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      # 3 Actualizar image.tag en values.yaml
      - name: Bump image tag
        run: |
          FILE=infra/charts/base/values.yaml
          yq -i '.image.repository = env(ACR)+"/pos-webapp" |
                 .image.tag        = env(TAG)' "$FILE"

      # 4 Crear / actualizar PR en pos-infra
      - uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_TOKEN_INFRA }}
          path: infra
          commit-message: "chore(webapp): bump image to $TAG"
          branch: bump/webapp-$TAG
          title: "chore(webapp): bump image to $TAG"
          body: "Auto-generated by pos-webapp CI"
          labels: automatic

